version: '2'
services:
  db:
    build: ./Database
    ports:
    - '3306:3306'
    volumes:
    - ./Database/mysql_data:/var/lib/mysql
    - ./Database/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'Alva_Server'
  web:
    build: ./Web
    ports:
    - '8080:8080'
    volumes:
    - ./html:/var/www/html
    depends_on:
    - db
    links:
    - db
  imagerecognition:
    build: ImageRecognition
    ports:
    - '8090:8090'
    depends_on:
    - db
    links:
    - db
  detectbarcode:
    build: BarcodeHWRecognition
    ports:
    - '8091:8091'
    volumes:
    - /dev/video0:/dev/video0
    - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
    - db
    links:
    - db
    command: >
      bash -c 'sh /usr/local/lib/Alva/StartProc.sh && sh /usr/local/lib/Alva/debug-loop.sh'
