version: '3'
services:
  rdb:
    build: Database
    ports:
    - '8136:3306'
    volumes:
    - ./Database/mysql_data:/var/lib/mysql
    - ./Database/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'Alva_Server'
  web:
    build: Web
    ports:
    - 80:80
    volumes:
    - ./html:/var/www/html
    depends_on:
    - rdb
  acs:
    build: ACS
    volumes:
    - ./ACS/app:/app/
    ports:
    - 8131:3031
    depends_on:
    - rdb
    environment:
      TZ: "Asia/Tokyo"
  nginx:
    build: ./S2A
    volumes:
    - ./S2A/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 8182:80
    depends_on:
    - acs
    - rdb
    - web
    - redis
    environment:
      TZ: "Asia/Tokyo"
  redis:
    build: Redis
    command: redis-server
    volumes:
    - ./Redis/redis-data:/data
    ports:
    - 8179:6379

#  detectbarcode:
#    build: BarcodeRecognitionServer
#    ports:
#    - '8091:8091'
#    devices:
#    - "/dev/video0:/dev/video0"
#    depends_on:
#    - rdb
#    command: >
#      bash -c 'sh /usr/local/lib/Alva/debug-loop.sh && python /usr/local/lib/Alva/ReadBarcode'
