version: '3'
services:
  rdb:
    build: Database
    ports:
    - 8136:3306
    volumes:
    - ./Database/mysql_data:/var/lib/mysql
    - ./Database/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'Alva_Server'
  web:
    build: Web
    #ports:
    #- 80:80
    volumes:
    - ./html:/var/www/html
    depends_on:
    - rdb
  acs:
    build: ACS
    volumes:
    - ./ACS/app:/app/
    ports:
    - 8131:3031
    depends_on:
    - rdb
    - acstaskreminder
    environment:
      TZ: "Asia/Tokyo"
  acstaskreminder:
    build: ACS_taskreminder
    volumes:
    - ./ACS_taskreminder/app:/app/
    ports:
    - 8231:3031
    depends_on:
    - rdb
    environment:
      TZ: "Asia/Tokyo"
  acsinfo:
    build: ACS_info
    volumes:
    - ./ACS_info/app:/app/
    ports:
    - 8331:3031
    depends_on:
    - rdb
    - acs
    environment:
      TZ: "Asia/Tokyo"
  nginx:
    build: ./S2A
    volumes:
    - ./S2A/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 8182:80
    depends_on:
    - acs
    - rdb
    - web
    - redis
    environment:
      TZ: "Asia/Tokyo"
  redis:
    build: Redis
    command: redis-server
    ports:
    - 8179:6379

  https-portal:
    image: steveltn/https-portal:1.0.0
    ports:
    - 80:80
    restart: always
    environment:
      DOMAINS: 'alva2018.com -> http://web:80'
      # STAGE: 'production'
      # FORCE_RENEW: 'true'