version: '3'
services:
  rdb:
    build: Database
    ports:
    - '3306:3306'
    volumes:
    - ./Database/mysql_data:/var/lib/mysql
    - ./Database/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'Alva_Server'
  web:
    build: Web
    ports:
    - 80:80
    volumes:
    - ./html:/var/www/html
    depends_on:
    - rdb
  alvacomserver:
    build: ACS
    volumes:
    - ./ACS/Applications:/app/
    ports:
    - 5000:5000
    depends_on:
    - rdb
  redis:
    build: Redis
    command: redis-server --appendonly yes --requirepass password
    volumes:
    - ./Redis/redis-data:/data
    ports:
    - 6379:6379
#  detectbarcode:
#    build: BarcodeRecognitionServer
#    ports:
#    - '8091:8091'
#    devices:
#    - "/dev/video0:/dev/video0"
#    depends_on:
#    - rdb
#    command: >
#      bash -c 'sh /usr/local/lib/Alva/debug-loop.sh && python /usr/local/lib/Alva/ReadBarcode'
