version: '3'
services:
  db:
    build: Database
    ports:
    - '3306:3306'
    volumes:
    - ./Database/mysql_data:/var/lib/mysql
    - ./Database/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'Alva_Server'
  web:
    build: Web
    ports:
    - 80:80
    volumes:
    - ./html:/var/www/html
    depends_on:
    - db
  alvacomserver:
    build: ACS
    depends_on:
    - db
    volumes:
    - .:/usr/src/app
    - vendor_bundle:/usr/src/app/vendor/bundle
    ports:
    - "3000:3000"
    entrypoint:
    - bin/rails
    - s
    - -b
    - 0.0.0.0
#  imagerecognition:
#    build: ImageRecognition
#    ports:
#    - '8090:8090'
#    depends_on:
#    - db
#  detectbarcode:
#    build: BarcodeRecognitionServer
#    ports:
#    - '8091:8091'
#    devices:
#    - "/dev/video0:/dev/video0"
#    depends_on:
#    - db
#    command: >
#      bash -c 'sh /usr/local/lib/Alva/debug-loop.sh && python /usr/local/lib/Alva/ReadBarcode'