DROP TABLE IF EXISTS D_BookShelf;
CREATE TABLE `D_BookShelf` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `XGrid_Place` int(10) NOT NULL DEFAULT '0',
  `YGrid_Plave` int(10) NOT NULL DEFAULT '0',
  `exist_S` int(1) DEFAULT '0',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;