CREATE TABLE `D_Barcode` (
  `Number` int(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Barcode` int(1000) NOT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;